# Generated by Django 3.1.4 on 2020-12-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caixote',
            fields=[
                ('perc_uso', models.FloatField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'caixote',
            },
        ),
        migrations.CreateModel(
            name='Dht11',
            fields=[
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('humidade', models.FloatField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dht11',
            },
        ),
        migrations.CreateModel(
            name='Mq135',
            fields=[
                ('alcohol', models.FloatField(blank=True, null=True)),
                ('co2', models.FloatField(blank=True, null=True)),
                ('nh4', models.FloatField(blank=True, null=True)),
                ('co', models.FloatField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'mq135',
            },
        ),
    ]
