# Generated by Django 3.1.4 on 2020-12-30 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_se_pagina', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caixote',
            old_name='perc_uso',
            new_name='perc_utilizacao',
        ),
    ]
